name: Build, test and publish a target extension

on:
  workflow_call:
    inputs:
      extension_name:
        description: "The PostgreSQL extension to build (directory name)"
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: false

permissions: {}

jobs:
  testbuild:
    name: Build ${{ inputs.extension_name }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      # Required by the cosign step
      id-token: write
    outputs:
      metadata: ${{ steps.build.outputs.metadata }}
      images: ${{ steps.images.outputs.images }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
        with:
          platforms: 'linux/arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build and push
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # v6
        id: build
        env:
          BUILDX_METADATA_PROVENANCE: disabled
          environment: testing
          registry: ghcr.io/${{ github.repository_owner }}
          revision: ${{ github.sha }}
        with:
          files: ./docker-bake.hcl,./${{ inputs.extension_name }}/metadata.hcl
          push: true

      # From bake's metadata, extract each unique tag (e.g. the ones with the timestamp)
      - name: Generated images
        env:
          BUILD_METADATA: ${{ steps.build.outputs.metadata }}
        id: images
        run: |
          echo "images=$(jq -c '[ .[]."image.name" | split(",")[] | select(test("[0-9]{12}")) ]' <<< "$BUILD_METADATA")" >>  "$GITHUB_OUTPUT"

      # Even if we're testing we sign the images, so we can push them to production later if that's required
      - name: Install cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3
        # See https://github.blog/security/supply-chain-security/safeguard-container-signing-capability-actions/
        # and https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml for more details on
        # how to use cosign.
      - name: Sign images
        env:
          BUILD_METADATA: ${{ steps.build.outputs.metadata }}
        run: |
          jq -r '.[] | (."image.name" | sub(",.*";"")) + "@" + ."containerimage.digest"' <<< "$BUILD_METADATA" | \
            xargs cosign sign --yes

  security:
    name: Security checks
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      security-events: write
    needs:
      - testbuild
    strategy:
      fail-fast: false
      matrix:
        image: ${{fromJson(needs.testbuild.outputs.images)}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Security checks
        uses: cloudnative-pg/postgres-containers/.github/actions/security-scans@main
        with:
          image: "${{ matrix.image }}"
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          dockerfile: "${{ inputs.extension_name }}/Dockerfile"

  smoke-test:
    name: Smoke test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    needs:
      - testbuild
    strategy:
      fail-fast: false
      matrix:
        image: ${{fromJson(needs.testbuild.outputs.images)}}
        cnpg: ["main", "1.27", "1.28"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install Task
        uses: go-task/setup-task@0ab1b2a65bc55236a3bc64cde78f80e20e8885c2 # v1.0.0

      - name: Install Dagger
        env:
          # renovate: datasource=github-tags depName=dagger/dagger versioning=semver
          DAGGER_VERSION: 0.19.10
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh

      - name: Set up environment
        run: |
          task e2e:setup-env

      - name: Generate Chainsaw testing values
        run: |
          task e2e:generate-values EXTENSION_IMAGE="${{ matrix.image }}" TARGET="${{ inputs.extension_name }}"

      - name: Run e2e tests
        run: |
          # Get Kind cluster internal kubeconfig
          task e2e:export-kubeconfig KUBECONFIG_PATH=./kubeconfig INTERNAL=true

          task e2e:test TARGET="${{ inputs.extension_name }}" KUBECONFIG_PATH="./kubeconfig"

  copytoproduction:
    name: Copy images to production
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    needs:
      - testbuild
      - security
      - smoke-test
    permissions:
      contents: read
      packages: write
      # Required by the cosign step
      id-token: write
    steps:
      - name: Copy to production
        uses: cloudnative-pg/postgres-containers/.github/actions/copy-images@main
        with:
          bake_build_metadata: "${{ needs.testbuild.outputs.metadata }}"
          registry_user: ${{ github.actor }}
          registry_token: ${{ secrets.GITHUB_TOKEN }}
